
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cwh
 */
public class scheduledOrders extends javax.swing.JFrame {

    /**
     * Creates new form scheduledOrders
     */
    public scheduledOrders() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jbtExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Date: 11/11/2017");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 148, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Order Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 60, 115, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Deliver Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 60, 104, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 60, 65, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Contact Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(760, 60, 132, 20);

        jLabel2.setText("1001");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 36, 20);

        jLabel7.setText("1002");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 140, 36, 20);

        jLabel8.setText("1003");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 170, 36, 20);

        jLabel9.setText("1004");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 210, 36, 20);

        jLabel10.setText("1005");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 250, 36, 20);

        jLabel11.setText("1006");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 280, 36, 20);

        jLabel12.setText("1007");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 320, 36, 20);

        jLabel13.setText("10.00 a.m.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(150, 100, 78, 20);

        jLabel14.setText("11.45 a.m.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(150, 140, 78, 20);

        jLabel15.setText("12.00 p.m.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(150, 170, 79, 20);

        jLabel16.setText("1.00 p.m.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(160, 210, 70, 20);

        jLabel17.setText("1.30 p.m.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(160, 240, 70, 20);

        jLabel18.setText("3.00 p.m.");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(160, 280, 70, 20);

        jLabel19.setText("3.45 p.m.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(160, 320, 70, 20);

        jLabel20.setText("173, Jalan Tengah, Taman Tengah, 33000 K.L.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(270, 100, 335, 20);

        jLabel21.setText("Apple Condominium, B3, L-8, 56000 K.L.");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(270, 140, 294, 20);

        jLabel22.setText("88, Jalan Timur 3, Taman Timur, 56100 K.L.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(270, 170, 320, 20);

        jLabel23.setText("901, Jalan Cerdas, Taman Segar, 33100 K.L.");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(270, 210, 317, 20);

        jLabel24.setText("123, Jalan S/22, Taman Matahari, 55000 K.L.");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(270, 250, 322, 20);

        jLabel25.setText("Orange Condominium, Level 2, 101, 33000 K.L.");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(270, 280, 341, 20);

        jLabel26.setText("53, Jalan Bunga, Taman Bungahari, 56000 K.L.");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(270, 320, 335, 20);

        jLabel27.setText("01690336900");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(790, 100, 99, 20);

        jLabel28.setText("038899113");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(810, 140, 81, 20);

        jLabel29.setText("0189999999");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(800, 170, 90, 20);

        jLabel30.setText("0126480477");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(800, 210, 90, 20);

        jLabel31.setText("0191234567");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(800, 240, 90, 20);

        jLabel32.setText("0128089700");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(800, 280, 90, 20);

        jLabel33.setText("0163027643");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(800, 320, 90, 20);

        jbtExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtExit.setText("Exit");
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtExit);
        jbtExit.setBounds(10, 370, 86, 29);

        jButton1.setText("Shortest Route");
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 320, 140, 20);

        jButton2.setText("Shortest Route");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 100, 140, 20);

        jButton3.setText("Shortest Route");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 140, 140, 20);

        jButton4.setText("Shortest Route");
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 170, 140, 20);

        jButton5.setText("Shortest Route");
        getContentPane().add(jButton5);
        jButton5.setBounds(610, 210, 140, 20);

        jButton6.setText("Shortest Route");
        getContentPane().add(jButton6);
        jButton6.setBounds(610, 250, 140, 20);

        jButton7.setText("Shortest Route");
        getContentPane().add(jButton7);
        jButton7.setBounds(610, 280, 140, 20);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgcolor.jpg"))); // NOI18N
        jLabel36.setText("jLabel36");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(0, 0, 900, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        JOptionPane.showMessageDialog(null,"Are you sure you want to exit?");
        this.setVisible(false);
        MainPage m = new MainPage();
        m.setVisible(true);
    }//GEN-LAST:event_jbtExitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"Check shortest route?");
        this.setVisible(false);
        shortestRoute1 s = new shortestRoute1();
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        shortestRoute2 s = new shortestRoute2();
        s.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduledOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduledOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduledOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduledOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduledOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtExit;
    // End of variables declaration//GEN-END:variables
}
